// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, cloudflare (build-only),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

// GitHub Pages serves the project at /jackpot-joy-finder/ — Vite needs the
// path prefix in production builds. The actual GH Pages bootstrap is a
// separate esbuild bundle generated by scripts/prerender.ts (we cannot add
// another Rollup input here because TanStack Start's start-manifest-plugin
// throws "multiple entries detected" when more than one entry chunk exists).
const isProd = process.env.NODE_ENV === "production";

export default defineConfig({
  vite: {
    base: isProd ? "/jackpot-joy-finder/" : "/",
  },
});
